- hosts: all
  become: yes
  become_method: sudo
  remote_user: vagrant
  environment:
    http_proxy: "{{ http_proxy | default() }}"
    https_proxy: "{{ https_proxy | default() }}"
    no_proxy: "{{ no_proxy | default() }}"
  roles:
    - role: reallyenglish.cloudstack-init
    - role: reallyenglish.sshd
  vars:
    sshd_config:
      # allow root using register ssh key
      # XXX user vagrant still exists but considered as safe enough because
      # password authetication is disabled and the insecure public key has been
      # removed.
      #
      # XXX if you remove `vagrant` user, the shutdown will be hard-reset that
      # causes file system corruption.
      PermitRootLogin: without-password
      PasswordAuthentication: "no"
      UseDNS: "no"
      UsePAM: "no"
      Subsystem: "sftp {{ sshd_sftp_server }}"
