---
all:
  hosts:
    ansible-freebsd-10.3-amd64:
      ansible_ssh_host: 192.168.212.100
      ansible_extra_vars:
        ansible_python_interpreter: /usr/local/bin/python
    ansible-openbsd-6.0-amd64:
      ansible_ssh_host: 192.168.212.100
      ansible_extra_vars:
        ansible_python_interpreter: /usr/local/bin/python
